#!/usr/bin/env sh
# Checks the self-signed cert's remaining validity; if it's within
# RENEW_THRESHOLD_DAYS of expiring, regenerates it and gracefully reloads
# nginx (no downtime — nginx -s reload picks up the new cert/key without
# dropping connections). Meant to run on a schedule via cron (see
# docs/deployment.md for the crontab entry).
#
# Every run is logged to nginx/certs/renewal.log. On any failure — openssl
# error, reload error, or the cert somehow still expiring soon right after
# a renewal attempt — an ERROR line goes to syslog (`logger`, so it shows
# up in `journalctl`/`/var/log/syslog` for anyone monitoring the host) and,
# if CERT_ALERT_WEBHOOK_URL is set in the environment, a POST is sent
# there too. Unset the webhook to skip that step entirely — nothing here
# requires an external alerting service to work.
#
# Usage: ./nginx/renew-cert-if-needed.sh
# Typically invoked by cron, not run by hand.

set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
CERT_FILE="$SCRIPT_DIR/certs/fullchain.pem"
LOG_FILE="$SCRIPT_DIR/certs/renewal.log"
RENEW_THRESHOLD_DAYS="${RENEW_THRESHOLD_DAYS:-30}"
COMPOSE_FILE="$REPO_DIR/docker-compose.prod.yml"

log() {
    # timestamped line to both stdout (so cron mail/logs capture it if
    # configured) and the dedicated renewal log
    msg="$(date -u '+%Y-%m-%dT%H:%M:%SZ') $1"
    echo "$msg" | tee -a "$LOG_FILE"
}

alert() {
    # Failure path: syslog always, webhook only if configured.
    reason="$1"
    logger -t cert-renewal -p user.err "IMS cert renewal FAILED: $reason" 2>/dev/null || true
    log "ALERT: $reason"

    if [ -n "${CERT_ALERT_WEBHOOK_URL:-}" ]; then
        curl -fsS -X POST -H "Content-Type: application/json" \
            -d "{\"text\":\"IMS TLS cert renewal failed: $reason\"}" \
            "$CERT_ALERT_WEBHOOK_URL" \
            >/dev/null 2>&1 || log "WARN: alert webhook POST itself failed (network/URL issue) — check CERT_ALERT_WEBHOOK_URL"
    fi
}

mkdir -p "$SCRIPT_DIR/certs"
touch "$LOG_FILE"

if [ ! -f "$CERT_FILE" ]; then
    log "No existing cert at $CERT_FILE — generating one now."
    if ! "$SCRIPT_DIR/generate-self-signed-cert.sh" >>"$LOG_FILE" 2>&1; then
        alert "initial cert generation failed — see $LOG_FILE"
        exit 1
    fi
    log "Initial cert generated."
    RELOAD_NEEDED=1
else
    # Seconds until expiry, via openssl's -checkend (0 = expired already).
    THRESHOLD_SECONDS=$((RENEW_THRESHOLD_DAYS * 86400))
    if openssl x509 -in "$CERT_FILE" -checkend "$THRESHOLD_SECONDS" -noout >/dev/null 2>&1; then
        log "Cert still valid for more than $RENEW_THRESHOLD_DAYS days — nothing to do."
        exit 0
    fi

    log "Cert expires within $RENEW_THRESHOLD_DAYS days — regenerating."
    if ! "$SCRIPT_DIR/generate-self-signed-cert.sh" >>"$LOG_FILE" 2>&1; then
        alert "cert regeneration failed — see $LOG_FILE"
        exit 1
    fi
    RELOAD_NEEDED=1
fi

# Sanity-check the new cert isn't itself already expiring soon (catches a
# broken/short-lived cert being generated by mistake) before reloading.
if ! openssl x509 -in "$CERT_FILE" -checkend "$((7 * 86400))" -noout >/dev/null 2>&1; then
    alert "newly generated cert is still within 7 days of expiry — refusing to reload nginx with it. Check generate-self-signed-cert.sh's DAYS argument."
    exit 1
fi

if [ "${RELOAD_NEEDED:-0}" = "1" ]; then
    if ! docker compose -f "$COMPOSE_FILE" exec -T nginx nginx -s reload >>"$LOG_FILE" 2>&1; then
        alert "new cert written but nginx reload failed — nginx may still be serving the old/expiring cert. Check 'docker compose -f $COMPOSE_FILE ps nginx'."
        exit 1
    fi
    log "nginx reloaded successfully with the new cert."
fi

log "Renewal check complete."